name: Setup Sleet
author: David G. Moore, Jr., <david@dgmjr.io>
description: Sets up the Sleet utility for managing NuGet packages.

branding:
  icon: cloud-snow
  color: white

inputs:
  source:
    required: true
    description: The Sleet source URL
  key:
    required: true
    description: The Sleet API key
  name:
    required: true
    description: The Sleet API key
    default: Sleet

runs:
  using: compositetuh
  steps:
    - id: Ensure-sleet-is-installed
      shell: bash
      run: |
        sleetExists=$(dotnet tool list --global | grep sleet)
        if [ -z "$sleetExists" ]; then
          echo "sleet tool already exists: $sleetExists; checking for updates..."
          dotnet tool update --global sleet
        else
          echo "sleet tool not found; installing..."
          dotnet tool install --global sleet
        fi
